// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmnuxwbqtzbemcgpfkly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtbnV4d2JxdHpiZW1jZ3Bma2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTYzNzEsImV4cCI6MjA3MTUzMjM3MX0.AAWIqrRX6IKmkYgqqshEzQKoSDVg6rN_J0i7yEdftLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});